<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ZeTwitchMiner</RootNamespace>
    <AssemblyName>ZeTwitchMiner</AssemblyName>
    <Version>0.2.0</Version>
    <Authors>zuckerigprod</Authors>
    <Company>zuckerigprod</Company>
    <Product>ZeTwitchMiner</Product>
    <Description>Twitch drops miner</Description>
    <Copyright>(c) 2026 zuckerigprod, https://github.com/zuckerigprod</Copyright>
    <RepositoryUrl>https://github.com/zuckerigprod/ZeTwitchMiner</RepositoryUrl>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
    <InvariantGlobalization>false</InvariantGlobalization>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishAot>true</PublishAot>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <OptimizationPreference>Size</OptimizationPreference>
    <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
    <DebuggerSupport>false</DebuggerSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <StackTraceSupport>true</StackTraceSupport>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <EmbeddedResource Include="Lang\*.json" LogicalName="Lang.%(Filename).json" />
    <EmbeddedResource Include="Twitch\twitch.json" LogicalName="twitch.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.22" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Lucide.Avalonia" Version="0.2.25" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
  </ItemGroup>

</Project>
